//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public Communication()
        {
            this.FichierCommunications = new HashSet<FichierCommunication>();
        }
    
        public int idCOM { get; set; }
        public string titreCOM { get; set; }
        public string contenuCOM { get; set; }
        public System.DateTime dateCOM { get; set; }
        public int idUTIL { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ICollection<FichierCommunication> FichierCommunications { get; set; }
    }
}
