//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConseilAdministration
    {
        public int idCA { get; set; }
        public string nomCA { get; set; }
        public string prenomCA { get; set; }
        public string descriptionCA { get; set; }
        public int idROLECA { get; set; }
    
        public virtual REF_RoleCA REF_RoleCA { get; set; }
    }
}
