//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int idCON { get; set; }
        public string courrielCON { get; set; }
        public string nomEtablissementCON { get; set; }
        public string codePostaleCON { get; set; }
        public string villePostaleCON { get; set; }
        public string nomEtablissementMembreCON { get; set; }
        public string rueMembreCON { get; set; }
        public string villeMembreCON { get; set; }
        public int idClub { get; set; }
    }
}
