//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groupe
    {
        public Groupe()
        {
            this.GroupeEntraineurs = new HashSet<GroupeEntraineur>();
            this.HoraireGroupes = new HashSet<HoraireGroupe>();
            this.Membres = new HashSet<Membre>();
        }
    
        public int idGRP { get; set; }
        public int idNIVSESS { get; set; }
        public string descriptionGRP { get; set; }
        public string photoGRP { get; set; }
        public System.DateTime dateCreationGRP { get; set; }
        public Nullable<System.DateTime> dateSuppression { get; set; }
        public int valideNiveauGRP { get; set; }
    
        public virtual ICollection<GroupeEntraineur> GroupeEntraineurs { get; set; }
        public virtual ICollection<HoraireGroupe> HoraireGroupes { get; set; }
        public virtual NiveauSession NiveauSession { get; set; }
        public virtual ICollection<Membre> Membres { get; set; }
    }
}
