//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoraireGroupe
    {
        public int idHOR { get; set; }
        public int idGRP { get; set; }
        public int idJOUR { get; set; }
        public string horaireDebut { get; set; }
        public string horaireFin { get; set; }
    
        public virtual Groupe Groupe { get; set; }
        public virtual REF_Jour REF_Jour { get; set; }
    }
}
