//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiveauSession
    {
        public NiveauSession()
        {
            this.Groupes = new HashSet<Groupe>();
        }
    
        public int idNIVEAU_SESSION { get; set; }
        public int idNIVEAU { get; set; }
        public int idSESSION { get; set; }
        public int duree { get; set; }
        public decimal tarif { get; set; }
        public decimal affiliation { get; set; }
        public decimal competitions { get; set; }
        public Nullable<System.DateTime> dateSuppression { get; set; }
    
        public virtual ICollection<Groupe> Groupes { get; set; }
        public virtual Niveau Niveau { get; set; }
        public virtual Session Session { get; set; }
    }
}
