//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int idPAIEMENT { get; set; }
        public int idMEMBRE { get; set; }
        public int idSESSION { get; set; }
        public int idTYPEPAIEMENT { get; set; }
        public System.DateTime dateSaisie { get; set; }
        public System.DateTime date { get; set; }
        public decimal montant { get; set; }
        public string note { get; set; }
        public bool encaisse { get; set; }
    
        public virtual REF_TypePaiement REF_TypePaiement { get; set; }
        public virtual Session Session { get; set; }
        public virtual Membre Membre { get; set; }
    }
}
