//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partenaire
    {
        public int idPAR { get; set; }
        public string nomPAR { get; set; }
        public string urlPAR { get; set; }
        public string logoPAR { get; set; }
        public int idClub { get; set; }
    }
}
