//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class H2017_PW_Equipe6Entities : DbContext
    {
        public H2017_PW_Equipe6Entities()
            : base("name=H2017_PW_Equipe6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<ConseilAdministration> ConseilAdministrations { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Courriel> Courriels { get; set; }
        public virtual DbSet<DatePaiement> DatePaiements { get; set; }
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<Entraineur> Entraineurs { get; set; }
        public virtual DbSet<FichierCompetition> FichierCompetitions { get; set; }
        public virtual DbSet<Groupe> Groupes { get; set; }
        public virtual DbSet<GroupeEntraineur> GroupeEntraineurs { get; set; }
        public virtual DbSet<GroupeMembre> GroupeMembres { get; set; }
        public virtual DbSet<HoraireGroupe> HoraireGroupes { get; set; }
        public virtual DbSet<Inscription> Inscriptions { get; set; }
        public virtual DbSet<LiensUtile> LiensUtiles { get; set; }
        public virtual DbSet<Membre> Membres { get; set; }
        public virtual DbSet<Niveau> Niveaux { get; set; }
        public virtual DbSet<NiveauSession> NiveauSessions { get; set; }
        public virtual DbSet<Offre> Offres { get; set; }
        public virtual DbSet<Paiement> Paiements { get; set; }
        public virtual DbSet<Partenaire> Partenaires { get; set; }
        public virtual DbSet<PhotoCompetition> PhotoCompetitions { get; set; }
        public virtual DbSet<PhotoSpectacle> PhotoSpectacles { get; set; }
        public virtual DbSet<REF_ContenuTexte> REF_ContenuTexte { get; set; }
        public virtual DbSet<REF_Jour> REF_Jour { get; set; }
        public virtual DbSet<REF_RoleCA> REF_RoleCA { get; set; }
        public virtual DbSet<REF_RoleEntraineur> REF_RoleEntraineur { get; set; }
        public virtual DbSet<REF_Saison> REF_Saison { get; set; }
        public virtual DbSet<REF_Secteur> REF_Secteur { get; set; }
        public virtual DbSet<REF_TypePaiement> REF_TypePaiement { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Spectacle> Spectacles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Texte> Textes { get; set; }
        public virtual DbSet<TypeUtilisateurREF> TypeUtilisateurREFs { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<FormulaireInscritption> FormulaireInscritptions { get; set; }
    }
}
