//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_RoleCA
    {
        public REF_RoleCA()
        {
            this.ConseilAdministrations = new HashSet<ConseilAdministration>();
        }
    
        public int idROLECA { get; set; }
        public string descriptionROLECA { get; set; }
        public int idClub { get; set; }
    
        public virtual ICollection<ConseilAdministration> ConseilAdministrations { get; set; }
        public virtual Club Club { get; set; }
    }
}
