//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_TypePaiement
    {
        public REF_TypePaiement()
        {
            this.Paiements = new HashSet<Paiement>();
        }
    
        public int idTYPEPAIEMENT { get; set; }
        public string nom { get; set; }
    
        public virtual ICollection<Paiement> Paiements { get; set; }
    }
}
