//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secteur
    {
        public Secteur()
        {
            this.Niveaux = new HashSet<Niveau>();
        }
    
        public int idSECTEUR { get; set; }
        public string nomSECTEUR { get; set; }
        public string descriptionSECTEUR { get; set; }
        public int idCLUB { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual ICollection<Niveau> Niveaux { get; set; }
    }
}
