//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.DatePaiements = new HashSet<DatePaiement>();
            this.Inscriptions = new HashSet<Inscription>();
            this.Paiements = new HashSet<Paiement>();
            this.NiveauSessions = new HashSet<NiveauSession>();
        }
    
        public int idSESSION { get; set; }
        public int idSAISON { get; set; }
        public int annee { get; set; }
        public bool estActif { get; set; }
        public bool dejaEteActif { get; set; }
        public bool inscriptionEnCours { get; set; }
        public System.DateTime dateDebut { get; set; }
        public string detailsAncienMembre { get; set; }
        public string detailsNouveauMembre { get; set; }
    
        public virtual ICollection<DatePaiement> DatePaiements { get; set; }
        public virtual ICollection<Inscription> Inscriptions { get; set; }
        public virtual ICollection<Paiement> Paiements { get; set; }
        public virtual REF_Saison REF_Saison { get; set; }
        public virtual ICollection<NiveauSession> NiveauSessions { get; set; }
    }
}
