//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeUtilisateurREF
    {
        public TypeUtilisateurREF()
        {
            this.Utilisateurs = new HashSet<Utilisateur>();
        }
    
        public int typeUTIL { get; set; }
        public string descriptionUTIL { get; set; }
    
        public virtual ICollection<Utilisateur> Utilisateurs { get; set; }
    }
}
