//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2017_PW_Equipe6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.Communications = new HashSet<Communication>();
            this.Entraineurs = new HashSet<Entraineur>();
            this.GroupeEntraineurs = new HashSet<GroupeEntraineur>();
        }
    
        public int idUTIL { get; set; }
        public int typeUTIL { get; set; }
        public bool entrainerChefUTIL { get; set; }
        public string nomUTIL { get; set; }
        public string prenomUTIL { get; set; }
        public string courrielUTIL { get; set; }
        public string adresseUTIL { get; set; }
        public string villeUTIL { get; set; }
        public string codePostalUTIL { get; set; }
        public string telephoneUTIL { get; set; }
        public string mdpUTIL { get; set; }
        public Nullable<System.DateTime> dateSuppression { get; set; }
        public int idCLUB { get; set; }
    
        public virtual ICollection<Communication> Communications { get; set; }
        public virtual ICollection<Entraineur> Entraineurs { get; set; }
        public virtual ICollection<GroupeEntraineur> GroupeEntraineurs { get; set; }
        public virtual TypeUtilisateurREF TypeUtilisateurREF { get; set; }
    }
}
